api:
  insecure: true
log:
  level: INFO
providers:
  file:
    filename: /etc/traefik/dynamic.yaml
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
          entryPoint:
            to: websecure
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: ""
