version: "3.9"

x-common-variables: &common-variables
  KEYCLOAK_URL:
  KEYCLOAK_REALM:
  KEYCLOAK_CLIENT_ID:
  KEYCLOAK_REDIRECT_URI:

x-kong-config:
  &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-off}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: kong-db
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-09-23T03-47-50Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  env_file:
    - ./conf/minio/minio.env
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5
  networks:
      - hostnet

services:
  orion:
    image: fiware/orion:3.10.1
    container_name: orion
    profiles: [ "middleware", "orion" ]
   # image: fiware/orion-ld:1.4.0
    hostname: orion
    depends_on:
      - mongodb
    networks:
      - hostnet
    ports:
      - "1026:1026"
    command: -dbhost mongodb -logLevel DEBUG
    #command: -dbhost mongodb -logLevel DEBUG -forwarding -experimental

  draco:
    image: draco
    build: ./build/draco
    profiles: [ "middleware", "draco" ]
    hostname: draco
    container_name: draco
    networks:
      - hostnet
    ports:
        # NIFI web UI (https)
        - 8443:8443
        # Listen AAS
        - 8085:8085
        # Listen Orion
        - 8086:8086
    env_file:
        - conf/draco/nifi.env
    tty: true     
    volumes:
      - ./conf/draco/templates:/opt/nifi/nifi-current/templates

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    profiles: [ "middleware", "iotagent-ui" ]
    hostname: mongodb
    networks:
      - hostnet
    ports:
      - 27017:27017
    command: --bind_ip_all
    volumes:
      - mongodb_volume:/data
  
  mosquitto:
    image: eclipse-mosquitto:2.0
    profiles: [ "middleware", "minio" ]
    hostname: mosquitto
    networks:
      - hostnet
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./conf/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  grafana:
    image: grafana/grafana:10.2.3
    profiles: [ "middleware", "grafana" ]
    hostname: grafana
    container_name: grafana
    restart: always
    networks:
      - hostnet
    volumes:
      - grafanavolume:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana

  pgadmin:
    image: dpage/pgadmin4:8.4
    profiles: [ "middleware" ]
    hostname: pgadmin
    container_name: pgadmin4
    restart: always
    networks:
      - hostnet
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.it"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
      - pgadminvolume:/var/lib/pgadmin

  postgres:
    image: postgres
    profiles: ["middleware"]
    container_name: middleware-postgres
    hostname: postgres
    networks:
      - hostnet
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  # starts 4 docker containers running minio server instances.
  # using nginx reverse proxy, load balancing, you can access
  # it through port 9000.
  minio1:
    <<: *minio-common
    profiles: [ "minio" ]
    hostname: minio1
    container_name: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    profiles: [ "minio" ]
    hostname: minio2
    container_name: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    profiles: [ "minio" ]
    hostname: minio3
    container_name: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    profiles: [ "minio" ]
    hostname: minio4
    container_name: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  reverse-proxy:
    image: nginx:1.19.2-alpine
    profiles: [ "reverse-proxy" ]
    container_name: reverse-proxy
    hostname: nginx
    networks:
      - hostnet
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificates/pioneer.crt:/etc/nginx/cert.crt
      - ./certificates/pioneer.key:/etc/nginx/cert.key
    ports:
      - "9000:9000"
      - "9001:9001"
      - "80:80"
      - "443:443"
  
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    container_name: keycloak
    hostname: keycloak
    profiles: [ "keycloak" ]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: default_database
      DB_USER: username
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false
      PROXY_ADDRESS_FORWARDING: true
      KEYCLOAK_FRONTEND_URL: https://localhost/auth/
      KC_PROXY: edge
    networks:
      - hostnet
    ports:
        - 8080:8080
    depends_on:
        - keycloak-db

  keycloak-db:
    image: postgres
    profiles: ["keycloak"]
    hostname: keycloak-db
    container_name: keycloak-db
    networks:
      - hostnet
    ports:
    - 5434:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - kc_postgres_volume:/var/lib/postgresql/data/

  iotagent-opcua:
    image: iotagent4fiware/iotagent-opcua:2.2.7
    profiles: [ "agents", "opcua" ]
    hostname: iotagent-opcua
    container_name: iotagent-opcua
    # depends_on:
    #   - mongodb
    #   - orion
    networks:
      - hostnet
    ports:
      - "4041:4041"
      - "9229:9229"
    environment:
      - "CONFIGURATION_TYPE=auto"
      - "CONFIG_RETRIEVAL=false"
      - "DEFAULT_KEY=iot"
      - "DEFAULT_TRANSPORT=OPCUA"
      - "IOTA_LOGLEVEL=DEBUG"
      - "IOTA_TIMESTAMP=true"
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_CB_NGSIVERSION=v2"
      - "IOTA_CB_NGSILDCONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
      - "IOTA_CB_SERVICE=opcua_pioneer"
      # It depends on use case e.g. "smc", "waam"
      - "IOTA_CB_SUBSERVICE=/smc"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_MONGO_HOST=mongodb"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagent_opcua"
      - "IOTA_SERVICE=opcua_pioneer"
      - "IOTA_SUBSERVICE=/smc"
      - "IOTA_PROVIDER_URL=http://iotagent-opcua:4041"
      - "IOTA_DEVICEREGDURATION=P20Y"
      - "IOTA_DEFAULTTYPE=Device"
      - "IOTA_DEFAULTRESOURCE=/iot/opcua"
      - "IOTA_EXPLICITATTRS=true"
      - "IOTA_EXTENDED_FORBIDDEN_CHARACTERS=[]"
      - "IOTA_AUTOPROVISION=true"
      - "IOTA_EXPRESS_LIMIT=50mb"
      # It depends on use case. OPCUA Server address
      - "IOTA_OPCUA_ENDPOINT=opc.tcp://opcuaserverhost:5001/UA/Server"
      - "IOTA_OPCUA_SECURITY_MODE=None"
      - "IOTA_OPCUA_SECURITY_POLICY=None"
      #- "IOTA_OPCUA_SECURITY_USERNAME=null"
      #- "IOTA_OPCUA_SECURITY_PASSWORD=null"
      - "IOTA_OPCUA_UNIQUE_SUBSCRIPTION=false"
      - "IOTA_OPCUA_SUBSCRIPTION_NOTIFICATIONS_PER_PUBLISH=1000"
      - "IOTA_OPCUA_SUBSCRIPTION_PUBLISHING_ENABLED=true"
      - "IOTA_OPCUA_SUBSCRIPTION_REQ_LIFETIME_COUNT=100"
      - "IOTA_OPCUA_SUBSCRIPTION_REQ_MAX_KEEP_ALIVE_COUNT=10"
      - "IOTA_OPCUA_SUBSCRIPTION_REQ_PUBLISHING_INTERVAL=1000"
      - "IOTA_OPCUA_SUBSCRIPTION_PRIORITY=128"
      - "IOTA_OPCUA_MT_POLLING=false"
      - "IOTA_OPCUA_MT_AGENT_ID=age01_"
      - "IOTA_OPCUA_MT_ENTITY_ID=age01_smc"
      - "IOTA_OPCUA_MT_ENTITY_TYPE=Device"
      - "IOTA_OPCUA_MT_NAMESPACE_IGNORE=0,7"
      - "IOTA_OPCUA_MT_STORE_OUTPUT=true"
    volumes:
      - ./conf/iotagent-opcua:/opt/iotagent-opcua/conf

  iotagent-json:
    image: quay.io/fiware/iotagent-json:3.6.0
    profiles: [ "agents", "json" ]
    hostname: iotagent-json
    container_name: iotagent-json
    # depends_on:
    #   - mongodb
    networks:
      - hostnet
    ports:
      - "4042:4041"
      - "7896:7896"
    environment:
      - IOTA_CB_HOST=orion # name of the context broker to update context
      - IOTA_CB_PORT=1026 # port the context broker listens on to update context
      - IOTA_NORTH_PORT=4042
      - IOTA_REGISTRY_TYPE=mongodb #Whether to hold IoT device info in memory or in a database
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_DEFAULT_EXPRESSION_LANGUAGE=jexl
      - IOTA_TIMESTAMP=true # Supply timestamp information with each measurement
      - IOTA_CB_NGSI_VERSION=v2 # use NGSIv2 when sending updates for active attributes
      - IOTA_MONGO_HOST=mongodb # The host name of MongoDB
      - IOTA_MONGO_PORT=27017 # The port mongoDB is listening on
      - IOTA_MONGO_DB=iotagent_json # The name of the database used in mongoDB
      - IOTA_HTTP_PORT=7896 # The port used for device traffic over HTTP
      - IOTA_PROVIDER_URL=http://iotagent-json:4042
      - IOTA_DEFAULT_RESOURCE=/iot/json

  iotagent-aas:
    image: iotagent4fiware/iotagent-aas:1.0.1
    profiles: [ "agent", "aas" ]
    hostname: iotagent-aas
    container_name: iotagent-aas
    # depends_on:
    #   - mongodb
    #   - orion
    networks:
      - hostnet
    ports:
      - "4043:4041"
      - "7897:7897"
    environment:
      - "DEFAULT_KEY=iot"
      - "DEFAULT_TRANSPORT=HTTP"
      - "IOTA_LOGLEVEL=DEBUG"
      - "IOTA_TIMESTAMP=true"
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_CB_NGSIVERSION=v2"
      - "IOTA_CB_NGSILDCONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
      - "IOTA_CB_SERVICE=aas_pioneer"
      # It depends on use case e.g. "smc", "waam"
      - "IOTA_CB_SUBSERVICE=/smc"
      - "IOTA_NORTH_PORT=4043"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_MONGO_HOST=mongodb"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagent_aas"
      - "IOTA_SERVICE=aas_ticket"
      - "IOTA_SUBSERVICE=/demo"
      - "IOTA_PROVIDER_URL=http://iotagent-aas:4043"
      - "IOTA_DEVICEREGDURATION=P20Y"
      - "IOTA_DEFAULTTYPE=Device"
      - "IOTA_DEFAULTRESOURCE=/iot/aas"
      - "IOTA_EXPLICITATTRS=true"
      - "IOTA_EXTENDED_FORBIDDEN_CHARACTERS=[]"
      - "IOTA_AUTOPROVISION=true"
      - "IOTA_MQTT_PROTOCOL=mqtt"
      - "IOTA_MQTT_HOST=mosquitto"
      - "IOTA_MQTT_PORT=1883"
      - "IOTA_MQTT_CA="
      - "IOTA_MQTT_CERT="
      - "IOTA_MQTT_KEY="
      - "IOTA_MQTT_REJECT_UNAUTHORIZED=true"
      - "IOTA_MQTT_USERNAME="
      - "IOTA_MQTT_PASSWORD="
      - "IOTA_MQTT_QOS=0"
      - "IOTA_MQTT_RETAIN=false"
      - "IOTA_MQTT_RETRIES=5"
      - "IOTA_MQTT_RETRY_TIME=5"
      - "IOTA_MQTT_KEEPALIVE=60"
      - "IOTA_MQTT_AVOID_LEADING_SLASH=false"
      - "IOTA_MQTT_DISABLED=false"
      - "IOTA_HTTP_PORT=7897"
      - "IOTA_HTTP_TIMEOUT=1000"
      - "IOTA_HTTP_KEY="
      - "IOTA_HTTP_CERT="
      # It depends on use case. AAS Server address
      - "IOTA_AAS_ENDPOINT=http://aasserverhost:9000/aas"
      - "IOTA_AAS_MT_AGENT_ID=age01_"
      - "IOTA_AAS_MT_ENTITY_ID=aas_smc"
      - "IOTA_AAS_MT_ENTITY_TYPE=Device"
      - "IOTA_AAS_MT_STORE_OUTPUT=true"
    volumes:
      - ./conf/iotagent-aas:/opt/iotagent-aas/conf

  iotiotagent-ui-spa:
    image: iotagent4fiware/iotiotagent-ui-spa:1.0.2
    profiles: [ "iotagent-ui" ]
    hostname: iotiotagent-ui-spa
    container_name: iotiotagent-ui-spa
    depends_on:
      - iotiotagent-ui-bff
    networks:
      - hostnet
    ports:
      - "8087:80"
    environment:
      <<: *common-variables
      BFF_API_BASE_URL: 'http://localhost:8000/agent/ui/api/v1'
      APP_BASE_HREF: '/iotagentui/'

  iotiotagent-ui-bff:
    image: iotagent4fiware/iotiotagent-ui-bff:1.0.0
    profiles: [ "iotagent-ui" ]
    hostname: iotiotagent-ui-bff
    container_name: iotiotagent-ui-bff
    depends_on:
      - mongodb
    networks:
      - hostnet
    ports:
      - "9005:9000"
    environment:
      <<: *common-variables
      NODE_ENV: 'true'
      PORT: '9000'
      MONGO_HOST: 'mongodb'
      MONGO_PORT: '27017'
      MONGO_DB: 'iotagent_ui'
      AUTH_SECRET: 'secret'
      ADMIN_ACCOUNT: 'true'

  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    container_name: kong-migrations
    command: kong migrations bootstrap
    profiles: [ "kong" ]
    depends_on:
      - kong-db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - hostnet
    restart: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    container_name: kong-migrations-up
    command: kong migrations up && kong migrations finish
    profiles: [ "kong" ]
    depends_on:
      - kong-db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - hostnet
    restart: on-failure
  
  kong-db-import:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    container_name: kong-db-import
    command: kong config db_import /opt/kong/kong.yaml
    profiles: [ "kong" ]
    depends_on:
      - kong-db
      - kong-migrations
      - kong-migrations-up
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    volumes:
      - ./conf/kong:/opt/kong
    networks:
      - hostnet
    restart: on-failure

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    container_name: kong
    profiles: [ "kong" ]
    hostname: kong
    depends_on:
      - kong-db
    user: "${KONG_USER:-kong}"
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_ADMIN_GUI_LISTEN: "${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    secrets:
      - kong_postgres_password
    networks:
      - hostnet
    ports:
      # The following two environment variables default to an insecure value (0.0.0.0)
      # according to the CIS Security test.
      - "${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:8000:8000/tcp"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:9443:9443/tcp"
      # Making them mandatory but undefined, like so would be backwards-breaking:
      # - "${KONG_INBOUND_PROXY_LISTEN?Missing inbound proxy host}:8000:8000/tcp"
      # - "${KONG_INBOUND_SSL_PROXY_LISTEN?Missing inbound proxy ssl host}:8443:8443/tcp"
      # Alternative is deactivating check 5.13 in the security bench, if we consider Kong's own config to be enough security here

      - "8001:8001/tcp"
      - "8444:8444/tcp"
      - "8002:8002/tcp"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
      - ./config:/opt/kong
    security_opt:
      - no-new-privileges

  kong-db:
    image: postgres:9.5
    container_name: kong-db
    profiles: [ "kong" ]
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${KONG_PG_DATABASE:-kong}",
          "-U",
          "${KONG_PG_USER:-kong}"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - 5433:5432
    networks:
      - hostnet
    volumes:
      - kong_data:/var/lib/postgresql/data

  token-refresh:
    image: token-refresh
    container_name: token-refresh
    build: ./build/token-refresh
    profiles: [ "kong" ]
    environment:
      KONG_ADMIN: "http://kong:8001"
      AUTH_ENDPOINT: "http://150.140.148.141:9000/oauth2/token"
      ROUTE_NAME: "aas-server-route"
      USERNAME: "admin"
      PASSWORD: "admin"
    networks:
      - hostnet

volumes:
  mongodb_volume:
  postgres_volume:
  kc_postgres_volume:
  pgadminvolume:
  grafanavolume:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
   hostnet:

secrets:
  kong_postgres_password:
    file: ./conf/kong/POSTGRES_PASSWORD
