version: "3.4"

x-common-variables: &common-variables
  KEYCLOAK_URL:
  KEYCLOAK_REALM:
  KEYCLOAK_CLIENT_ID:
  KEYCLOAK_REDIRECT_URI:

services:
  orion:
    image: fiware/orion:3.10.1
   # image: fiware/orion-ld:1.4.0
    hostname: orion
    depends_on:
      - mongodb
    networks:
      - hostnet
    ports:
      - "1026:1026"
    command: -dbhost mongodb -logLevel DEBUG
    #command: -dbhost mongodb -logLevel DEBUG -forwarding -experimental

  draco:
    image: draco
    build: ./build/draco
    hostname: draco
    container_name: draco
    networks:
      - hostnet
    ports:
        # NIFI web UI (https)
        - 8443:8443
        # Listen AAS
        - 8085:8085
        # Listen Orion
        - 8086:8086
    env_file:
        - conf/draco/nifi.env
    tty: true     
    volumes:
      - ./conf/draco/templates:/opt/nifi/nifi-current/templates

  mongodb:
    image: mongo:7.0.5
    hostname: mongodb
    networks:
      - hostnet
    ports:
      - 27017:27017
    command: --bind_ip_all
    volumes:
      - mongodb_volume:/data

  postgres:
    image: postgres:17.2
    hostname: postgres
    networks:
      - hostnet
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  # Settings and configurations that are common for all containers
  x-minio-common: &minio-common
    image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    expose:
      - "9000"
      - "9001"
    env_file:
      - ./conf/minio/minio.env
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # starts 4 docker containers running minio server instances.
  # using nginx reverse proxy, load balancing, you can access
  # it through port 9000.
  minio1:
    <<: *minio-common
    hostname: minio1
    networks:
      - hostnet
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    networks:
      - hostnet
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    networks:
      - hostnet
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    networks:
      - hostnet
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    networks:
      - hostnet
    volumes:
      - ./conf/minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  mosquitto:
    image: eclipse-mosquitto:2.0
    hostname: mosquitto
    networks:
      - hostnet
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./conf/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    command: start-dev
    env_file:
      - conf/keycloak/keycloak.env
    networks:
      - hostnet
    ports:
        - 8080:8080
    depends_on:
        - kc-postgres
  
  kc-postgres:
    image: postgres:17.2
    hostname: kc-postgres
    networks:
      - hostnet
    expose:
    - 5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak 
      POSTGRES_DB: keycloak
    volumes:
      - kc_volume:/var/lib/postgresql/data/

  iotagent-opcua:
    image: iotagent4fiware/iotagent-opcua:2.2.8
    hostname: iotagent-opcua
    depends_on:
      - mongodb
      - orion
    networks:
      - hostnet
    ports:
      - "4041:4041"
      - "9229:9229"
    env_file:
      - conf/iotagent-opcua/iotagent-opcua.env
    volumes:
      - ./conf/iotagent-opcua:/opt/iotagent-opcua/conf


  iotagent-json:
    image: quay.io/fiware/iotagent-json:3.6.0
    hostname: iotagent-json
    depends_on:
      - mongodb
    networks:
      - hostnet
    ports:
      - "4042:4041"
      - "7896:7896"
    env_file:
      - conf/iotagent-json/iotagent-json.env

  aas-proxy:
    build: ./build/aas-proxy
    hostname: aas-proxy
    networks:
      - hostnet
    ports:
      - 3001:3000
    env_file:
      - conf/aas-proxy/aas-proxy.env

  iotagent-aas:
    image: iotagent4fiware/iotagent-aas:1.0.2
    hostname: iotagent-aas
    depends_on:
      - mongodb
      - orion
      - aas-proxy
    networks:
      - hostnet
    ports:
      - "4043:4041"
      - "7897:7897"
    env_file:
      - conf/iotagent-aas/iotagent-aas.env
    volumes:
      - ./conf/iotagent-aas:/opt/iotagent-aas/conf

  iotagent-ui-spa:
    image: iotagent4fiware/iotagent-ui-spa:1.0.3
    hostname: iotagent-ui-spa
    depends_on:
      - iotagent-ui-bff
    networks:
      - hostnet
    ports:
      - "8087:80"
    environment:
      <<: *common-variables
      BFF_API_BASE_URL: 'http://localhost:9005/api/v1'

  iotagent-ui-bff:
    image: iotagent4fiware/iotagent-ui-bff:1.0.2
    hostname: iotagent-ui-bff
    depends_on:
      - mongodb
    networks:
      - hostnet
    ports:
      - "9005:9000"
    environment:
      <<: *common-variables
      NODE_ENV: 'true'
      PORT: '9000'
      MONGO_HOST: 'mongodb'
      MONGO_PORT: '27017'
      MONGO_DB: 'iotagent_ui'
      AUTH_SECRET: 'secret'
      ADMIN_ACCOUNT: 'true'

  grafana:
    image: grafana/grafana:10.2.3
    hostname: grafana
    container_name: grafana
    restart: always
    networks:
      - hostnet
    volumes:
      - grafanavolume:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin4
    restart: always
    networks:
      - hostnet
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.it"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
      - pgadminvolume:/var/lib/pgadmin

## By default, this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  mongodb_volume:
  postgres_volume:
  kc_volume:
  pgadminvolume:
  grafanavolume:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

networks:
   hostnet:
